"""API tests for POST /print — the core flow (Section 13 test #3).

Every test here uses the mock_print fixture: on a Windows dev box the real
windows.submit_pdf would find the real SumatraPDF and print actual paper.
With the mock, the background thread still runs, so the tests observe the
full lifecycle (201 → background thread → done, file deleted) through the
Event it signals.
"""

import zipfile
from io import BytesIO

from PIL import Image

ONE_MB = 1024 * 1024


def post_pdf(client, data, name="report.pdf", **kwargs):
    files = {"file": (name, data, "application/pdf")}
    return client.post("/print", files=files, **kwargs)


def make_png_bytes():
    """A tiny real PNG, generated by Pillow (no binary fixtures in the repo)."""
    buffer = BytesIO()
    Image.new("RGB", (8, 8), (200, 30, 30)).save(buffer, "PNG")
    return buffer.getvalue()


def make_docx_bytes():
    """The smallest ZIP detection treats as a DOCX (a word/ part inside)."""
    buffer = BytesIO()
    with zipfile.ZipFile(buffer, "w") as archive:
        archive.writestr("word/document.xml", b"<xml/>")
    return buffer.getvalue()


class TestPrintHappyPath:
    def test_upload_returns_201_with_queued_job(self, client, pdf_bytes, mock_print):
        response = post_pdf(client, pdf_bytes)

        assert response.status_code == 201
        body = response.json()
        assert body["status"] == "queued"
        assert body["filename"] == "report.pdf"
        assert body["size_bytes"] == len(pdf_bytes)
        assert body["job_id"]  # non-empty id the phone will poll

    def test_job_reaches_done_and_temp_file_is_deleted(
        self, client, pdf_bytes, mock_print, tmp_upload_dir, wait_for_status, wait_until
    ):
        job_id = post_pdf(client, pdf_bytes).json()["job_id"]

        job = wait_for_status(job_id, "done")
        assert job.printer  # the printer that accepted it is recorded

        # The unlink happens just after the status flips to done — wait for it.
        wait_until(
            lambda: not (tmp_upload_dir / f"{job_id}.pdf").exists(),
            message="printed job's temp file should be deleted",
        )

    def test_png_upload_prints_via_the_image_processor(
        self, client, mock_print, tmp_upload_dir, wait_for_status, wait_until
    ):
        response = client.post(
            "/print", files={"file": ("shot.png", make_png_bytes(), "image/png")}
        )

        assert response.status_code == 201
        job_id = response.json()["job_id"]

        job = wait_for_status(job_id, "done")
        assert job.format == "image"

        # The engine only ever sees a PDF (the converted page), never raw
        # image bytes — and it is named <job_id>.pdf so cleanup finds it.
        assert mock_print.pdf_path.suffix == ".pdf"
        assert mock_print.pdf_path.stem == job_id

        # Both the source upload and the converted page are cleaned up.
        wait_until(
            lambda: not list(tmp_upload_dir.glob(f"{job_id}.*")),
            message="image job's temp files should be deleted",
        )

    def test_docx_upload_prints_via_the_office_processor(
        self, client, mock_print, monkeypatch, tmp_upload_dir, wait_for_status, wait_until
    ):
        # LibreOffice itself is never run in tests (external executable):
        # available() is patched on and process() fakes the conversion,
        # exactly the seam spike T6 covers on real hardware.
        monkeypatch.setattr(
            "app.processors.office.OfficeProcessor.available", lambda self: True
        )

        def fake_convert(self, src, out_dir):
            pdf = out_dir / f"{src.stem}.pdf"
            pdf.write_bytes(b"%PDF- converted by (mocked) LibreOffice")
            return pdf

        monkeypatch.setattr(
            "app.processors.office.OfficeProcessor.process", fake_convert
        )

        response = client.post(
            "/print", files={"file": ("invoice.docx", make_docx_bytes(), "application/zip")}
        )

        assert response.status_code == 201
        job_id = response.json()["job_id"]

        job = wait_for_status(job_id, "done")
        assert job.format == "office"
        assert mock_print.pdf_path.suffix == ".pdf"  # engine only ever sees PDF
        assert mock_print.pdf_path.stem == job_id

        wait_until(
            lambda: not list(tmp_upload_dir.glob(f"{job_id}.*")),
            message="office job's temp files should be deleted",
        )

    def test_txt_upload_prints_via_the_real_text_renderer(
        self, client, mock_print, tmp_upload_dir, wait_for_status, wait_until
    ):
        # No mocking needed: reportlab is a Python library, so this runs
        # the REAL conversion inside the API flow.
        content = "hello from the phone\nline two with more text\n" * 10
        response = client.post(
            "/print", files={"file": ("notes.txt", content.encode(), "text/plain")}
        )

        assert response.status_code == 201
        job_id = response.json()["job_id"]

        job = wait_for_status(job_id, "done")
        assert job.format == "text"

        # The engine only ever sees a PDF named <job_id>.pdf. Its CONTENT
        # can't be read here — cleanup deletes it right after "done" — the
        # unit tests assert the rendered bytes.
        assert mock_print.pdf_path.suffix == ".pdf"
        assert mock_print.pdf_path.name == f"{job_id}.pdf"

        wait_until(
            lambda: not list(tmp_upload_dir.glob(f"{job_id}.*")),
            message="text job's temp files should be deleted",
        )


class TestPrintRejections:
    """Section 13 test #8 — bad files must be refused before printing."""

    def test_non_pdf_extension_rejected_with_415(self, client, pdf_bytes, mock_print):
        response = post_pdf(client, pdf_bytes, name="virus.exe")
        assert response.status_code == 415
        assert "pdf" in response.json()["detail"].lower()

    def test_renamed_text_file_rejected_by_magic_bytes(
        self, client, mock_print
    ):
        response = post_pdf(client, b"definitely not a pdf", name="fake.pdf")
        assert response.status_code == 415

    def test_oversized_file_rejected_with_413(self, client, monkeypatch, mock_print):
        monkeypatch.setattr("app.services.uploads.MAX_UPLOAD_MB", 1)
        response = post_pdf(client, b"%PDF-" + b"x" * ONE_MB, name="big.pdf")
        assert response.status_code == 413

    def test_rejected_files_never_reach_the_store(self, client, mock_print, tmp_upload_dir):
        post_pdf(client, b"not a pdf", name="fake.pdf")
        assert mock_print.called.is_set() is False  # no print attempted
        assert list(tmp_upload_dir.glob("*.pdf")) == []  # nothing stored

    def test_unsupported_image_type_rejected_with_415(self, client, mock_print):
        # HEIC (iPhone photos) is a Phase-2 rejection: detected as unknown
        # extension, refused with the "what IS supported" message.
        response = client.post(
            "/print", files={"file": ("photo.heic", b"whatever", "image/heic")}
        )
        assert response.status_code == 415
        assert "pdf" in response.json()["detail"].lower()


class TestPrintErrors:
    def test_disk_failure_returns_500(self, client, pdf_bytes, monkeypatch, mock_print):
        def broken_save(data, ext=".pdf"):
            raise OSError("disk full")

        monkeypatch.setattr("app.api.print.save_upload", broken_save)
        response = post_pdf(client, pdf_bytes)
        assert response.status_code == 500
        assert "disk full" in response.json()["detail"]


class TestPrintAuth:
    def test_pin_enforced_on_upload_when_configured(
        self, client, pdf_bytes, monkeypatch, mock_print
    ):
        monkeypatch.setattr("app.services.auth.API_PIN", "1234")

        no_header = post_pdf(client, pdf_bytes)
        wrong_pin = post_pdf(client, pdf_bytes, headers={"X-API-PIN": "0000"})
        correct = post_pdf(client, pdf_bytes, headers={"X-API-PIN": "1234"})

        assert no_header.status_code == 401
        assert wrong_pin.status_code == 401
        assert correct.status_code == 201

    def test_upload_open_when_no_pin_configured(self, client, pdf_bytes, mock_print):
        assert post_pdf(client, pdf_bytes).status_code == 201
